
name: Release Module

on: 
  push:
    branches:
      - master

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3

    - name: Get Version
      id: get-version
      run: echo  "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Zip
      id: zip
      working-directory: ./
      run: zip -r ./module-v${{steps.get-version.outputs.version}}.zip ./lang ./module ./LICENSE ./auto-fastforward.js ./module.json

    - name: Release 
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: Release v${{steps.get-version.outputs.version}}
        tag: ${{steps.get-version.outputs.version}}
        artifacts: "module-v${{steps.get-version.outputs.version}}.zip, module.json"
        allowUpdates: true
        draft: false
        prerelease: false

