
name: Release Module

on: 
  push:
    branches:
      - master

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3

    - name: Get Version
      id: get-version
      run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"
      shell: bash

    - name: Zip
      id: zip
      working-directory: ./
      run: zip -r ./module-v${{steps.get-version.outputs.version}}.zip ./lang ./module ./LICENSE ./auto-fastforward.js ./module.js

    - name: Release 
      id: release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        name: Release v${{steps.get-version.outputs.version}}
        draft: false
        prerelease: false
        token: ${{secrets.GITHUB_TOKEN}}
        tag: ${{steps.get-version.outputs.version}}

